name: Bug
description: Bug Ticket
title: "[Bug]: "
labels: ["Bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      value: ""
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduktionsschritte
      value: |
        - [ ] Schritt
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Erwartetes Verhalten
      value: ""
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Tatsächliches Verhalten
      value: ""
    validations:
      required: true
