name: Bug
title: "[Bug]: "
labels: ["Bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      placeholder: ""
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Schritte zur Reproduktion
      placeholder: |
        - [ ] Schritt
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Erwartetes Verhalten
      placeholder: ""
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Tatsächliches Verhalten
      placeholder: ""
    validations:
      required: true
