name: Bug
description: Bug Ticket
title: "[Bug]: "
labels: ["Bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: "Description"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        - [ ] Step
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: "Expected behavior"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: "Actual behavior"
    validations:
      required: true
