name: Bug
description: Bug Ticket
title: "[Bug] _____"

body:
  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      value: ""
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduktionsschritte
      value: |
        - [ ] _____
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Erwartetes Verhalten
      value: "_____"
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Tatsächliches Verhalten
      value: "_____"
    validations:
      required: true
