name: Epic
description: Epic Ticket
title: "[Epic]: "
labels: ["Epic"]

body:
  - type: textarea
    id: description
    attributes:
      label: User Story
      value: "Als **[Rolle]** möchte ich **[Feature]**, damit **[Nutzen]**."
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Akzeptanzkriterien
      value: |
        - [ ] Akzeptanzkriterium
    validations:
      required: true
