name: Epic
description: Epic Ticket
title: "[Epic]: "
labels: ["Epic"]

body:
  - type: textarea
    id: description
    attributes:
      label: User Story
      placeholder: "As a [role] I want [feature], so that [benefit]."
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] Acceptance criterion
    validations:
      required: true
