name: Epic
description: Epic Ticket
title: "[Epic]"

body:
  - type: textarea
    id: description
    attributes:
      label: User Story
      value: "Als **[_____]** möchte ich **[_____]**, damit **[_____]**."
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Akzeptanzkriterien
      value: |
        - [ ] _____
    validations:
      required: true
