name: Feature
description: Feature Ticket
title: "[Feature] "

body:
  - type: textarea
    id: description
    attributes:
      label: User Story
      value: "Als **[_____]** möchte ich **[_____]**, damit **[_____]**."
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Akzeptanzkriterien
      value: |
        - [ ] _____
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Aufgaben
      value: |
        #### Frontend
        - [ ] _____

        #### Backend
        - [ ] _____

        #### Sonstiges
        - [ ] _____
    validations:
      required: true