name: Feature
description: Feature Ticket
title: "[Feature]: "
labels: ["Feature"]

body:
  - type: textarea
    id: description
    attributes:
      label: User Story
      value: "Als **[Rolle]** möchte ich **[Feature]**, damit **[Nutzen]**."
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Akzeptanzkriterien
      value: |
        - [ ] Akzeptanzkriterium
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Aufgaben
      value: |
        - [ ] Aufgabe
    validations:
      required: true