name: Spike
description: Spike Ticket
title: "[Spike]"

body:
  - type: textarea
    id: description
    attributes:
      label: User Story
      value: "Als **[_____]** möchte ich **[_____]**, damit **[_____]**."
    validations:
      required: true

  - type: textarea
    id: research_goals
    attributes:
      label: Untersuchungsziele
      value: |
        - [ ] _____
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Aufgaben
      value: |
        #### Frontend
        - [ ] _____

        #### Backend
        - [ ] _____

        #### Sonstiges
        - [ ] _____
    validations:
      required: true