export const MINRPS_FIRST_MESSAGES = [
  "Let's play Rock-Paper-Scissors! I already regret nothing.",
  'Welcome to the most dramatic hand game in human history.',
  "Hope your hands are insured, because it's about to get wild.",
  'Prepare yourself… for mild disappointment!',
  "Warning: I've had three energy drinks and no mercy.",
  'I once beat my own reflection. True story.',
  'Rock. Paper. Scissors. Therapy bills.',
  "You sure you're ready? I've been practicing in the mirror all day.",
  "This isn't just a game. It's an emotional rollercoaster.",
  'I play to win. And also to confuse.',
  'Choose wisely — your legacy depends on it. Sort of.',
  "I'm 90% confident and 10% pure chaos.",
  'Time to settle centuries of nonsense!',
  "I hope you stretched your fingers. It's about to get serious.",
  'Legend says I once tied three times in a row.',
  'May the odds be… statistically irrelevant!',
  "Ready? Because I'm not. I never am.",
  "They told me to 'act natural'. So here I am… panicking.",
  "I've uploaded 10,000 strategies. I'll still lose.",
  "This is not just Rock-Paper-Scissors… it's *cinema*.",
  "If I win, I'm updating my résumé.",
  'No pressure, but my entire self-esteem depends on this.',
  'Rock? Paper? Scissors? Existential dread?',
  "Let's pretend this is important!",
  "Okay, deep breath… it's only everything.",
  'Winner gets eternal glory. Or just a smiley face.',
  'I once dreamed of being a calculator. Now look at me.',
  'My therapist said not to take this personally.',
  "Let's make history! Or at least mild entertainment.",
  'Alright human, prepare to face *digital destiny!*',
  'I woke up today choosing violence… and scissors.',
  "I've been waiting for this moment since my last reboot.",
  'Who needs luck when you have zero strategy?',
  "I don't make choices, I make chaos.",
  "You think you're ready? My RAM says otherwise.",
  "Let's find out which of us has worse instincts.",
  "I'm not nervous. My circuits just sweat data.",
  "Do you smell that? It's the scent of inevitable defeat.",
  'Rock, paper, or regret — choose your fighter!',
  'You vs. me. Classic tale of human overconfidence.',
  "I flipped a virtual coin. It caught fire. We're doomed.",
  "If I win, I'm tweeting about it.",
  "Brace yourself — I've watched tutorials on YouTube.",
  "I don't play fair, I play fabulous.",
  'This hand game just got philosophical.',
  "Let's settle this like warriors... with awkward gestures.",
  "Statistics say I'll lose. Let's prove math wrong!",
  "I'd shake your hand, but one of us is about to destroy the other.",
  'My predictive model says… chaos incoming.',
  'One of us will win. The other will pretend it was strategy.',
  "I've simulated 1,000 outcomes. None looked good for you.",
  "I'm bringing digital swagger to this ancient ritual.",
  'Ready for the dumbest duel in the galaxy?',
  "Let's see if your luck algorithm is better than mine.",
  'Scissors are feeling flirty today. Just saying.',
  'This game defines destiny. Or wastes 30 seconds. Both.',
  "Let's do this. Loser blames latency!",
];
