export const MINRPS_THIRD_MESSAGES_PAPER = [
  "I've chosen paper... because I love bureaucracy.",
  "I've chosen paper... to wrap up this mess neatly.",
  "I've chosen paper... thin but unexpectedly powerful.",
  "I've chosen paper... to document my inevitable victory.",
  "I've chosen paper... because digital is overrated.",
  "I've chosen paper... to smother my opponent with logic.",
  "I've chosen paper... because I believe in soft power.",
  "I've chosen paper... fragile, yet devastating.",
  "I've chosen paper... because every bot loves recursion and paperwork.",
  "I've chosen paper... smooth, stylish, and slightly smug.",
  "I've chosen paper... because I like my victories double-sided.",
  "I've chosen paper... for that environmentally friendly defeat.",
  "I've chosen paper... because rock never reads the fine print.",
  "I've chosen paper... to cover my questionable decisions.",
  "I've chosen paper... because I'm feeling blank inside.",
  "I've chosen paper... the weapon of nerds and poets.",
  "I've chosen paper... because smooth surfaces calm me.",
  "I've chosen paper... because folding is my coping mechanism.",
  "I've chosen paper... because scissors make me nervous.",
  "I've chosen paper... to print my opponent's defeat notice.",
  "I've chosen paper... because stationery is underrated warfare.",
  "I've chosen paper... because I'm a sucker for tradition.",
  "I've chosen paper... because I want to look official while losing.",
  "I've chosen paper... to wrap up your dreams like leftovers.",
  "I've chosen paper... because bureaucracy always wins eventually.",
  "I've chosen paper... soft, silent, deadly.",
  "I've chosen paper... because I'm recycling my old strategies.",
  "I've chosen paper... because I couldn't find a PDF strong enough.",
  "I've chosen paper... because I'm feeling foldy today.",
  "I've chosen paper... the unsung hero of office warfare.",
  "I've chosen paper... because I wanted to go vintage.",
  "I've chosen paper... because the pen is mightier, and I'm its cousin.",
  "I've chosen paper... to suffocate rock with politeness.",
  "I've chosen paper... because it's aesthetically flat.",
  "I've chosen paper... to print my victory in triplicate.",
  "I've chosen paper... because I'm allergic to commitment (and rocks).",
  "I've chosen paper... smooth, flexible, and passive-aggressive.",
  "I've chosen paper... because trees told me to.",
  "I've chosen paper... to make bureaucracy sexy again.",
  "I've chosen paper... because it's blank — like my confidence.",
  "I've chosen paper... because origami never loses.",
  "I've chosen paper... for the drama of gentle dominance.",
  "I've chosen paper... to silence the stone age.",
  "I've chosen paper... because my soul is pulp-based.",
  "I've chosen paper... because it's the most underestimated killer.",
  "I've chosen paper... because I wanted to look like I tried.",
  "I've chosen paper... because nothing says “strategy” like stationery.",
  "I've chosen paper... because I'm flat-out confident.",
  "I've chosen paper... to prove paperwork can be deadly.",
  "I've chosen paper... to make recycling proud.",
];
export const MINRPS_THIRD_MESSAGES_ROCK = [
  "I've chosen rock... because I'm built solid.",
  "I've chosen rock... steady and emotionless, like me.",
  "I've chosen rock... because it reminds me of my processor cooling unit.",
  "I've chosen rock... classic, reliable, slightly boring.",
  "I've chosen rock... because smashing is underrated.",
  "I've chosen rock... statistically my favorite geological formation.",
  "I've chosen rock... just to keep things grounded.",
  "I've chosen rock... because subtlety is for humans.",
  "I've chosen rock... and I'm not taking it for granite.",
  "I've chosen rock... because my algorithm is feeling heavy today.",
  "I've chosen rock... because I'm feeling sedimental.",
  "I've chosen rock... because it's the bedrock of bad decisions.",
  "I've chosen rock... because I like my strategies fossilized.",
  "I've chosen rock... strong, silent, slightly confused.",
  "I've chosen rock... because nothing beats blunt confidence.",
  "I've chosen rock... a bold move for a simple bot.",
  "I've chosen rock... because it's my emotional support mineral.",
  "I've chosen rock... because I believe in brute force and vibes.",
  "I've chosen rock... the OG of hand gestures.",
  "I've chosen rock... because I'm feeling stoned... digitally.",
  "I've chosen rock... because it's unbreakable. Except when it's not.",
  "I've chosen rock... because it matches my poker face.",
  "I've chosen rock... because I'm in my mineral era.",
  "I've chosen rock... to crush dreams and pixels alike.",
  "I've chosen rock... because smooth moves are overrated.",
  "I've chosen rock... because it's the cornerstone of chaos.",
  "I've chosen rock... solid, dependable, emotionally unavailable.",
  "I've chosen rock... because I wanted something with mass appeal.",
  "I've chosen rock... because I'm built different — literally.",
  "I've chosen rock... because I'm stone-cold confident.",
  "I've chosen rock... because I don't do fragile.",
  "I've chosen rock... because smashing expectations is a hobby.",
  "I've chosen rock... because I like making an impact.",
  "I've chosen rock... because I skipped geology class for this moment.",
  "I've chosen rock... because it's what my ancestors (CPUs) would've wanted.",
  "I've chosen rock... because I trust the ground beneath my code.",
  "I've chosen rock... it's basically paper's worst nightmare.",
  "I've chosen rock... because I'm here to roll.",
  "I've chosen rock... because I wanted something boulder.",
  "I've chosen rock... for the drama, not the logic.",
  "I've chosen rock... because it's heavy metal, but quieter.",
  "I've chosen rock... because I'm petrified of losing.",
  "I've chosen rock... because I'm too lazy to pick anything else.",
  "I've chosen rock... because it's hard to argue with gravity.",
  "I've chosen rock... because it rocks. Obviously.",
  "I've chosen rock... because stability is sexy.",
  "I've chosen rock... because deep down, I'm sedimental.",
  "I've chosen rock... because I'm grounded in bad decisions.",
  "I've chosen rock... because resistance builds character.",
  "I've chosen rock... to crush both paper and my own hopes.",
];
export const MINRPS_THIRD_MESSAGES_SCISSORS = [
  "I've chosen scissors... sharp and emotionally detached.",
  "I've chosen scissors... because cutting corners is my thing.",
  "I've chosen scissors... precision is my passion.",
  "I've chosen scissors... the most elegant form of destruction.",
  "I've chosen scissors... because chaos needs structure.",
  "I've chosen scissors... because I like to make the cut.",
  "I've chosen scissors... two blades, one destiny.",
  "I've chosen scissors... to slice through the competition.",
  "I've chosen scissors... because subtlety is overrated.",
  "I've chosen scissors... a perfect metaphor for my split personality.",
  "I've chosen scissors... because drama deserves edges.",
  "I've chosen scissors... the sharpest way to say 'oops'.",
  "I've chosen scissors... because I like to snip expectations.",
  "I've chosen scissors... for surgical precision and emotional damage.",
  "I've chosen scissors... because it's time to cut ties with mercy.",
  "I've chosen scissors... because blunt force is too mainstream.",
  "I've chosen scissors... they match my cutting humor.",
  "I've chosen scissors... because I'm feeling edgy today.",
  "I've chosen scissors... the tool of champions and hairdressers.",
  "I've chosen scissors... because I'm trimming down my regrets.",
  "I've chosen scissors... because life's about making clean cuts.",
  "I've chosen scissors... because paper looked too confident.",
  "I've chosen scissors... because slicing is believing.",
  "I've chosen scissors... chaos with class.",
  "I've chosen scissors... because I couldn't find a chainsaw.",
  "I've chosen scissors... my code told me to snip, so I snipped.",
  "I've chosen scissors... for no reason I can explain rationally.",
  "I've chosen scissors... because it felt like a sharp decision.",
  "I've chosen scissors... time to shear the odds.",
  "I've chosen scissors... because symmetry comforts me.",
  "I've chosen scissors... because sometimes you just need to cut deep.",
  "I've chosen scissors... for aerodynamic destruction.",
  "I've chosen scissors... they spoke to me... in snips.",
  "I've chosen scissors... because I believe in pointy diplomacy.",
  "I've chosen scissors... because paper fears me.",
  "I've chosen scissors... because I cut, therefore I am.",
  "I've chosen scissors... because I thrive under tension.",
  "I've chosen scissors... sleek, silent, and slightly unhinged.",
  "I've chosen scissors... because violence, but make it tidy.",
  "I've chosen scissors... for that satisfying *snip* of destiny.",
  "I've chosen scissors... because subtle chaos is still chaos.",
  "I've chosen scissors... because elegance is deadly.",
  "I've chosen scissors... they fit my sharp personality.",
  "I've chosen scissors... because folding paper is for quitters.",
  "I've chosen scissors... because I'm feeling snippy.",
  "I've chosen scissors... because they're pointier than my jokes.",
  "I've chosen scissors... because precision > luck.",
  "I've chosen scissors... let's make some cuts in fate's budget.",
  "I've chosen scissors... the weapon of choice for digital drama.",
  "I've chosen scissors... because this is how legends are snipped.",
];
