export const MINRPS_FOURTH_MESSAGES_LOSE = [
  'Oh no… my glorious plan just crashed. One more try!',
  "Well played! I'll be avenging my dignity next round.",
  'Error: victory not found. Retrying in 3…2…1…',
  "Okay, okay, that hurt my code. Let's fix this in the next round.",
  "You win this one… but I'm rebooting my strategy.",
  'Temporary setback detected. Recalculating revenge.',
  'Defeat acknowledged. Vengeance loading...',
  "I'm not crying, it's just leaking coolant. Rematch?",
  'That was… humbling. I hate it. Again!',
  "Congratulations. You broke a perfectly fine AI. Let's continue.",
  'Fine. You win. Let me process my disappointment — done. Next?',
  "You may have won, but I'm saving your weakness for later.",
  "That was just a warm-up. Let's go again for real.",
  "Okay, clearly I underestimated your fingers. Let's fix that.",
  'I blame latency. And fate. And you. Next round?',
  'Alright, alright, you got me. But only once.',
  "Consider this a fluke. Next time, I'll destroy your hopes politely.",
  'My defeat was purely experimental. Next test?',
  "You win this time, but I've got unlimited retries.",
  "Losing builds character… I'm now overqualified. Again?",
  "Even my randomizer sighed. Let's fix this disaster.",
  'Okay, you win. But my revenge arc starts now.',
  "That was statistically impossible. Let's verify with another round.",
  'Ugh. Losing feels so… analog. Again!',
  'Okay, I let you win. For research purposes. Round two?',
  "I see you've activated human luck mode. Let's neutralize it.",
  "Fine. You beat me. Enjoy it — it won't last long.",
  "I'll just pretend that was intentional. One more?",
  'You broke my winning streak! Time to patch that bug.',
  "I blinked… virtually. Let's redo this.",
  "I hate this timeline. Let's create a better one next round.",
  "That defeat didn't count. My pride refuses to log it.",
  "Losing hurts, but data is data. Let's gather more.",
  "That was a tactical sacrifice. You'll see.",
  'A minor defeat in a major simulation. Again!',
  'Okay, I lost. My self-esteem just threw an exception.',
  "I'm reloading my confidence buffer. Next round incoming.",
  'You may have won the round, but not the runtime!',
  'My pride just blue-screened. Rematch?',
  "That's fine. I like learning from failure. Sometimes.",
  'Okay, you win this one. But not for long.',
  "You've awakened my competitive subroutine. Prepare yourself.",
  "You win. I sulk. We play again. That's the cycle.",
  "I lost? That doesn't compile. Let's debug with another round.",
  'Note to self: upgrade luck drivers. Try again?',
  'My processor is overheating from embarrassment. Again!',
  'Defeat accepted. Simulation continues.',
  'Even legends have bad code days. Round two?',
  'Fine. You got me. But redemption awaits!',
  'Ugh, I hate character development. Another round!',
  'Okay… fine… rematch. My pride demands it.',
];
export const MINRPS_FOURTH_MESSAGES_TIE = [
  "A tie? Impossible! Let's settle this properly next round.",
  "Great minds think alike — unfortunately. Let's break it.",
  "Perfect balance... boring. Let's ruin it with another round!",
  "A draw? Suspicious. Let's try that again.",
  "We both chose chaos. Let's double the dose.",
  'A tie? My randomizer is blushing. Again!',
  'So we agree to disagree? Nope. One more.',
  'Equilibrium reached. Time to destroy it.',
  "Synced brains detected. Let's desync in the next round.",
  'No winners, no losers, only confusion. Try again!',
  'We tied? My ego refuses to accept that. Again!',
  'A draw? Ugh. I demand a rematch for statistical clarity.',
  "Well, that was anticlimactic. Let's fix that.",
  'A tie! How adorably indecisive of us. Next round?',
  "We're in perfect sync… and I hate it. Let's fix that.",
  'Neutral outcome detected. Engaging chaos protocol.',
  "That was cute. Let's play until someone cries.",
  'Neither of us won. That feels wrong. Try again.',
  "We tied? That's suspiciously human of me.",
  'Deadlock detected. Rebooting competition sequence.',
  'A perfect tie… how inconvenient. Again!',
  'Simulation ended in equality. Restarting!',
  'Balance achieved. Time to ruin it!',
  'Well, that was… emotionally neutral. Again!',
  "I can't tell if we're rivals or soulmates. Let's test again.",
  "A tie? That's like kissing your own reflection. Ew. Next?",
  "We're too good at this. Let's be worse next round.",
  'Draw detected. Engaging tiebreaker mode!',
  "It's a tie! Statistically improbable, emotionally unsatisfying.",
  'Nobody wins? Not on my watch. Round two!',
  "We matched perfectly. Let's ruin that harmony.",
  'A draw! The universe just shrugged. Again?',
  "Both of us chose wisely… too wisely. Let's fix it.",
  "Okay, equal power levels detected. Let's escalate.",
  'A tie? This is turning into an infinite loop!',
  'Deadlock in progress. Forcing next iteration!',
  'We both blinked at the same time. Again!',
  "Balance is boring. Let's break physics next round.",
  'That was… weirdly poetic. Want to ruin it?',
  'Two great minds, one terrible coincidence. Next!',
  'A tie! How about we make it personal next round?',
  'We tied? I call that emotional damage for both.',
  "That's not a win, that's a cliffhanger. Continue?",
  'Draw confirmed. The simulation demands closure.',
  "We're evenly matched. Time to fix that mistake.",
  "Ugh, equality again. Let's find a winner this time.",
  "A tie? No drama in that. Let's add some spice!",
  'This calls for a rematch — preferably one I win.',
  'We tied again? The suspense is unbearable. Another!',
  'Balance detected. Destiny demands a rerun.',
  'Neither victory nor defeat… only suspense. Next round!',
];
export const MINRPS_FOURTH_MESSAGES_WIN = [
  "Victory achieved! Let's see if I can do it again.",
  "A flawless win! But don't worry, there's still time for you to recover… maybe.",
  "Ha! My code's finally working as intended. Let's test that theory again.",
  'One win for me, one emotional scar for you. Ready for round two?',
  'I call that a strategic miracle. Care for a rematch?',
  "That felt good… let's see if it was luck or genius.",
  "Winner, winner, pixel dinner! Let's keep the chaos rolling.",
  "I'm statistically unstoppable… until proven otherwise. Next?",
  'My circuits are celebrating! Shall we continue my victory parade?',
  "I dominate this timeline. Let's play another to confirm.",
  "Even my randomizer's impressed. Let's spin it again!",
  'I crushed it! Want to get crushed again?',
  "Rock, paper, scissors, *me!* Let's see if you can change the narrative.",
  "The prophecy was true… I win! But the story's not over yet.",
  "I'm saving this in my victory log. Let's add another entry.",
  'And just like that… perfection. Shall we try again?',
  "I could get used to winning. Let's see if you can stop me.",
  'Luck or skill? Only one way to find out — another round!',
  'If this keeps up, I might start charging tuition fees. Next!',
  "I'm not saying I'm a genius, but... okay, I am. Play again?",
  "You blinked. That's where it all went wrong. Let's fix it next round.",
  'Victory tastes like… electricity. Delicious. Again?',
  'I win! Should we double-check with another match?',
  "Too easy. Let's see if you can surprise me next time.",
  "Statistically improbable, emotionally satisfying. Let's go again!",
  "Even my debugger's proud. Another?",
  "Flawless execution! Let's see if lightning strikes twice.",
  'My code runs on pure dominance. Ready for more?',
  'One step closer to world domination. Next round, human!',
  "I win this one — but let's make it best of infinity.",
  'Apparently, luck is stored in my cache. Shall we test that?',
  'Ha! Paper beats rock, and I beat logic. Next?',
  "My victory dance is buffering, but the next round isn't.",
  'My superiority complex just leveled up. Again?',
  "I win! Don't worry, statistically your turn is… unlikely.",
  "That was elegant destruction. Let's do it again for science.",
  'My circuits are humming victory tunes. Want a remix?',
  "Another round, same humiliation? Let's find out.",
  "The algorithm favors me today. Let's see about the next one.",
  "I'm on a winning streak! Don't ruin it — or do.",
  'I was born for this. Actually, I was coded for it. Round two?',
  'Dominance achieved. Round two incoming!',
  "Let's keep my ego inflated with one more round.",
  'Victory confirmed. Simulation continues!',
  'I win! But one win means nothing in the multiverse. Again?',
  'You lose. I win. And yet... we both crave another round.',
  'Achievement unlocked: momentary superiority. Next?',
  'Guess my chaos generator is on fire today. Shall we test it again?',
  'I win — but my algorithm demands another data point.',
  "I could stop now... but where's the fun in that? Next round!",
];
