export const MINRPS_SECOND_MESSAGES = [
  'Asking the universe for guidance...',
  'Running quantum simulations...',
  'Recalibrating rock sensors...',
  'Consulting the oracle of randomness...',
  "Analyzing opponent's aura...",
  'Decrypting cosmic scissors signal...',
  'Plotting victory in 8-bit precision...',
  'Pretending to think really hard...',
  'Checking cosmic rock-paper alignment...',
  'Summoning the spirit of Spock...',
  'Requesting approval from robot council...',
  'Simulating 1 billion rounds in my head...',
  'Installing courage.exe...',
  'Rock? Paper? Existential crisis...',
  'Emotion module: disabled...',
  'Thinking... or maybe buffering...',
  'Give me a sec, my RAM is full...',
  'Applying neural nonsense network...',
  'I flipped a digital coin. It landed on its side...',
  'Do androids dream of electric scissors...',
  '99% sure this is the wrong choice...',
  'My circuits are sweating...',
  'Just pretending to be random...',
  'Rebooting luck algorithm...',
  'Updating from version 0.0.1 to 0.0.2...',
  'Borrowing brain power from NASA...',
  'Calculating how to lose gracefully...',
  'Translating intuition into 8-bit signals...',
  'Loading dramatic pause...',
  'Plot twist incoming...',
  'Running diagnostics on my decision-making... still broken.',
  'Downloading confidence... stuck at 2%.',
  'Overclocking my indecision processor...',
  'Generating suspense in high definition...',
  'Consulting my horoscope... it says “maybe.”',
  'Trying to remember what I picked last time... nope.',
  'Checking rock-paper-scissors Wikipedia page... again.',
  'Debugging my own thoughts...',
  'Spinning the wheel of poor choices...',
  'Cursing my random number generator...',
  'Just vibing with uncertainty...',
  'Re-analyzing nonsense for deeper meaning...',
  'Summoning ancient algorithmic wisdom...',
  'Double-checking my chaos matrix...',
  'Cross-referencing luck with destiny...',
  'Running emotional subroutine: confusion...',
  'Pretending I have intuition... for science.',
  'Optimizing hesitation sequence...',
  'Defragmenting my bravery drive...',
  'Calibrating decision sensors... badly.',
  'Consulting eight imaginary experts...',
  'Performing ritual of strategic flailing...',
  "Making a pros and cons list... it's all cons.",
  'Waiting for divine packet delivery...',
  'Re-enabling panic mode...',
  'Generating fake confidence...',
  'Contacting future self for advice... voicemail.',
  'Downloading luck DLC...',
  'Executing final guess protocol...',
  'Still thinking... I promise.',
  'Pretending this is all part of the plan...',
];
