@baseUrl = http://localhost:3000/minrps
@gamesEndpoint = /games
@gameId = f00f8ec6-1fce-4446-b0ee-3a476bfe15bb

### GET /games
GET {{baseUrl}}{{gamesEndpoint}}
Accept: application/json


### POST /games
POST {{baseUrl}}{{gamesEndpoint}}
Accept: application/json
Content-Type: application/json

{
  "name": "Test Game"
}


### DELETE /games/{id}
DELETE {{baseUrl}}{{gamesEndpoint}}/{{gameId}}
Accept: application/json