@BASE_PATH = http://localhost:3000/minrps
@GAMES = games
@ID = f534f71c-d81b-43b1-b963-073cab444708
@PLAY = play
@VERSION = version


### GET /games
GET {{BASE_PATH}}/{{GAMES}}
Accept: application/json


### GET /games/{id}
GET {{BASE_PATH}}/{{GAMES}}/{{ID}}
Accept: application/json


### POST /games
POST {{BASE_PATH}}/{{GAMES}}
Accept: application/json
Content-Type: application/json

{
  "name": "Test Game"
}


### DELETE /games/{id}
DELETE {{BASE_PATH}}/{{GAMES}}/{{ID}}
Accept: application/json


### POST /play
POST {{BASE_PATH}}/{{PLAY}}
Accept: application/json
Content-Type: application/json

{
  "player1Move": "rock"
}
