name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  node-ci:
    name: ${{ matrix.app.name }} - lint, test, build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
          - { name: client, path: client }
          - { name: server, path: server }

    defaults:
      run:
        working-directory: ${{ matrix.app.path }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            ${{ matrix.app.path }}/package-lock.json
      
      - name: Install Chrome (Angular Client)
        if: matrix.app.name == 'client'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libxss1 \
            libasound2t64 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libxkbcommon0 \
            libxcomposite1 \
            libxrandr2 \
            libgbm1 \
            libgtk-3-0 \
            fonts-liberation

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci
        continue-on-error: false

      - name: Build
        run: npm run build
